import RainbowkitProvider from '@/components/providers/RainbowkitProvider';
import MuiThemeProvider from '@/components/providers/ThemeProvider';
import Layout from '@/components/Layout';
import { ToastContainer } from 'react-toastify';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Meta Node Stake',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className="min-h-full flex flex-col">
        <MuiThemeProvider>
          <RainbowkitProvider>
            <ToastContainer
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              toastClassName="custom-toast"
              className="custom-toast-body"
              progressClassName="custom-toast-progress"
            />
            <Layout>{children}</Layout>
          </RainbowkitProvider>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
